### ISSUE TITLE
unexpected keyword argument 'stochastic_xy' 

### ISSUE THREAD

**Issue by thwanguk** [junsu-kim97/HIGL#1]
Hello

Thanks for sharing the code. 

I've got the following error when running the script:

./scripts/higl_ant_maze_u.sh dense 10e5 0 2
Logging in ./logs/higl
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    run_higl(args)
  File "./HIGL/higl/train.py", line 130, in run_higl
    stochastic_sigma=args.stochastic_sigma),
TypeError: make() got an unexpected keyword argument 'stochastic_xy'

I greatly appreciate it if you could look into it. Thank you!

**Comment by junsu-kim97** [comment]
Hi, thanks for the interest in our work.

To reproduce your error message, I re-run the code, but it works well without raising the error.

So, If you could provide me more descriptions about your errors, It would be more helpful to address the issue.

I suspect that the error may comes from our modification in AntEnv class in goal_env/mujoco/ant.py in order to handle stochastic environments.

Also, I highly recommend you to check the ant.py and 

`import gym`
`from goal_env import *`
`from goal_env.mujoco import *`
is included in higl/train.py

Junsu
